### ISSUE TITLE
Doesn't allow to send mail with empty password

### ISSUE THREAD

**Issue by ajaywhiz** [cake-contrib/Cake.Email#42] opened 2020-08-29 00:31 UTC
Doesn't work if the SMTP password is blank. I tested the same thing with using native .NET SmtpClient and not passing the password, that is how the credentials are setup, was able to send mail
```
mailClient.EnableSsl = false;
mailClient.Host = "<my smtp server>";
mailClient.Port = 25;
mailClient.Credentials = new NetworkCredential("<my username>", string.Empty);
```

**Comment by Jericho** [comment] 2020-08-29 16:12
When you say "doesn't work" what do you mean exactly? 
Do you get an error message? 
Stack trace? 
Do you have steps to reproduce this problem?
Can you share your Cake script?
Any additional details you can share?

**Comment by ajaywhiz** [comment] 2020-08-30 00:52
Error I get is `Failed to send email: 5.7.3 Authentication unsuccessful`


Here is the cake script
```
#addin nuget:?package=Cake.Email&version=0.8.0&loaddependencies=true

using Cake.Email.Common;


Task("SendEmail")    
    .Does(() =>
{
    try
    {        
        var result = Email.SendEmail(
                senderName: "Bamboo Build", 
                senderAddress: "<sender email>",
                recipients: new[]
                {
                    new MailAddress("<some email>", "<some name>")                    
                },
                subject: "This is a test",
                htmlContent: "<html><body>This is a test</body></html>",
                textContent: "This is a test",
                attachments: null,
                settings: new EmailSettings 
                {
                    SmtpHost = "<smpt server>",
                    Port = 25,
                    EnableSsl = false,
                    Username = "<user name>",
                    Password = string.Empty 
                }
                //NOTE there is no password required for SMTP username I have
        );

        if (result.Ok)
        {
            Information("Email succcessfully sent");
        }
        else
        {
            Error("Failed to send email: {0}", result.Error);
        }
    }
    catch(Exception ex)
    {
        Error("{0}", ex);
    }
});

var target = Argument("target", "Default");

Task("Default")
  .IsDependentOn("SendEmail")
  .Does(() =>
{
  Information("Hello World!");
});

RunTarget(target);
```

**Comment by Jericho** [comment] 2020-09-02 14:32
`5.7.3 Authentication unsuccessful` is an error code returned from your SMTP server so it will be hard for anybody other than you to investigate but here are a few suggestions I can think of:
- try a null value instead of a an empty string
- try changing the password to a non-empty value

**Comment by ajaywhiz** [comment] 2020-09-02 21:59
If I pass null I get
```
Failed to send email: Value cannot be null.
Parameter name: password
```
I can't change the password. That's how the account is setup and used by other teams. People performing builds on other platforms use this credentials e.g. gradle etc.   

Looks like MailKit doesn't consider blank password.

**Comment by ajaywhiz** [comment] 2020-09-03 01:18
If you skip `client.Authenticate` mail gets sent successfully.

Is there a possibility for you to add a setting to skip auth?

**Comment by Jericho** [comment] 2020-09-03 23:59
My Cake addin is already designed to skip `Authenticate` if the [username is blank](https://github.com/cake-contrib/Cake.Email/blob/develop/Source/Cake.Email/EmailProvider.cs#L257). This is useful in cases where the SMTP server does not require authentication.

I was under the impression that we were investigating a problem with a username having a blank password; but now you are saying that you don't need authentication at all?!?!?

By the way, I assume you published this [nuget package](https://www.nuget.org/packages/Cake.SendMail/) to help investigate your problem. Please make sure to delete this package so we don't end up with a duplicate. Thanks.

**Comment by gep13** [comment] 2020-09-07 10:04
@Jericho looks like the package has been updated on NuGet:

![image](https://user-images.githubusercontent.com/1271146/92376066-ee138100-f0f9-11ea-8bf2-115312e92220.png)

**Comment by Jericho** [comment] 2020-09-07 13:09
Thank you @ajaywhiz for unlisting the duplicate package. Were you able to skip authentication with a blank username as I indicated? Did it resolve the problem?

**Comment by Jericho** [comment] 2020-09-09 14:16
@ajaywhiz I am going to assume you were able to figure out how to skip authentication and close this issue.

**Closed as completed by Jericho** 2020-09-09 14:16 UTC

**Comment by ajaywhiz** [comment] 2020-09-09 15:18
Sorry, wasn't able to retry. Will try again and let you know

**Comment by ajaywhiz** [comment] 2020-09-09 15:21
If I pass a blank username. I get this error

`Failed to send email: The client and server cannot communicate, because they do not possess a common algorithm`

**Comment by Jericho** [comment] 2020-09-09 15:23
So in other words, you can't skip authentication.

**Comment by Jericho** [comment] 2020-09-09 15:27
You indicated that you can't change the password of the user since it's being used by other processes so what about you create a brand new user?
